# -*- coding: utf-8 -*-
"""ML_neural6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lsXfgwSx9wg4WFcOsyj2VqXW_uPWY0wf
"""

!pip install keras tensorflow -U

import numpy as np

df=np.loadtxt('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv', delimiter=',')

df

df.shape

#input data
x=df[:,:8]

#output data
y=df[:,8]

y

from collections import Counter
Counter(y)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

#create model
model = Sequential()

#input layer 
model.add(Dense(12, input_dim=8, activation='relu'))

#hidden layers
model.add(Dense(8, activation='relu'))
model.add(Dense(8, activation='relu'))

#output layer
model.add(Dense(1, activation='sigmoid'))

#compile the model
model.compile(loss='binary_crossentropy', optimizer='adam',
             metrics=['accuracy'])

#Train the model
model.fit(x,y,epochs=100, batch_size=10)

#Train the model again
model.fit(x,y,epochs=200, batch_size=10)

#Evaluate the model
model.evaluate(x,y)

model.summary()

