# -*- coding: utf-8 -*-
"""ML_rules5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1THhrzhKvboRsLPruFlomJ1UBUUkOi4-_
"""

#install the 
!pip install mlxtend

import pandas as pd
import csv
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

df=[]
with open ('Market_Basket_Optimisation.csv') as file:
    reader=csv.reader(file,delimiter=',')
    for row in reader:
        df+=[row]

df.head()

df[1:10]

len(df)

#transcation encoder , this is impro to do in assco rule
te=TransactionEncoder()
x=te.fit_transform(df)
x

df = pd.DataFrame(x, columns=te.columns_)

te.columns_

len(te.columns_)

df.head()

#apriori algo
#1.Find frequent itemsets
freq_itemset = apriori(df, min_support=0.01, use_colnames=True)

freq_itemset

#find the rules
rules=association_rules(freq_itemset, metric='confidence', 
                        min_threshold=0.25)

rules

rules= rules[['antecedents','consequents', 'antecedent support','consequent support']]

rules.head()

#check for pusring cake
rules[rules['antecedents']=={'cake'}]

